apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: uk05dsv68-nodejs-gitops
  description: This is GitOps manifest for uk05dsv68-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=uk05dsv68-nodejs
    backstage.io/kubernetes-id: uk05dsv68-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: uk05dsv68-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:uk05dsv68-nodejs
