apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uk05dsv68-nodejs
  janus-idp.io/tekton: uk05dsv68-nodejs
  backstage.io/kubernetes-id: uk05dsv68-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: uk05dsv68-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
