apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uk05dsv68-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uk05dsv68-nodejs 
  name: uk05dsv68-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: uk05dsv68-nodejs 
